-- Drop original notes if exists
DROP TABLE IF EXISTS notes;
-- Makes table stores names of cars makes

DROP TABLE IF EXISTS makes;
CREATE TABLE makes (id bigint not null primary key, make_name varchar(100) not null);

INSERT INTO makes(id, make_name) VALUES(1, 'Peugeot');
INSERT INTO makes(id, make_name) VALUES(2, 'Citroen');
INSERT INTO makes(id, make_name) VALUES(3, 'Renault');
INSERT INTO makes(id, make_name) VALUES(4, 'Opel');
INSERT INTO makes(id, make_name) VALUES(5, 'VW');
INSERT INTO makes(id, make_name) VALUES(6, 'Skoda');
INSERT INTO makes(id, make_name) VALUES(7, 'Toyota');
INSERT INTO makes(id, make_name) VALUES(8, 'Ford');
INSERT INTO makes(id, make_name) VALUES(9, 'Chevrolet');
INSERT INTO makes(id, make_name) VALUES(10, 'Mazda');
INSERT INTO makes(id, make_name) VALUES(11, 'Audi');
INSERT INTO makes(id, make_name) VALUES(12, 'Fiat');
INSERT INTO makes(id, make_name) VALUES(13, 'BMW');
INSERT INTO makes(id, make_name) VALUES(14, 'Mercedes');

DROP TABLE IF EXISTS models;
-- Models table stores names of cars models within specific makes (referenced by make_id)
CREATE TABLE models (id bigint not null primary key, model_name varchar(100) not null, make_id bigint not null references makes);

INSERT INTO models(id, model_name, make_id) VALUES(1199, '308',1);
INSERT INTO models(id, model_name, make_id) VALUES(103, '1007',1);
INSERT INTO models(id, model_name, make_id) VALUES(13, '807',1);
INSERT INTO models(id, model_name, make_id) VALUES(10, '407',1);
INSERT INTO models(id, model_name, make_id) VALUES(1290, '207 Facelift',1);
INSERT INTO models(id, model_name, make_id) VALUES(1268, '3008',1);
INSERT INTO models(id, model_name, make_id) VALUES(811, '207',1);
INSERT INTO models(id, model_name, make_id) VALUES(262, '107',1);
INSERT INTO models(id, model_name, make_id) VALUES(102, '406',1);
INSERT INTO models(id, model_name, make_id) VALUES(1228, 'Partner Tepee',1);
INSERT INTO models(id, model_name, make_id) VALUES(1229, '407 Facelift',1);
INSERT INTO models(id, model_name, make_id) VALUES(14, 'Partner',1);
INSERT INTO models(id, model_name, make_id) VALUES(1201, '4007',1);
INSERT INTO models(id, model_name, make_id) VALUES(1265, '206+',1);
INSERT INTO models(id, model_name, make_id) VALUES(1, '206',1);
INSERT INTO models(id, model_name, make_id) VALUES(1266, 'Bipper Tepee',1);
INSERT INTO models(id, model_name, make_id) VALUES(256, '607',1);
INSERT INTO models(id, model_name, make_id) VALUES(265, '307',1);
INSERT INTO models(id, model_name, make_id) VALUES(64, 'C4',2);
INSERT INTO models(id, model_name, make_id) VALUES(62, 'C2',2);
INSERT INTO models(id, model_name, make_id) VALUES(1185, 'C-Crosser',2);
INSERT INTO models(id, model_name, make_id) VALUES(1298, 'C3',2);
INSERT INTO models(id, model_name, make_id) VALUES(63, 'Stare C3',2);
INSERT INTO models(id, model_name, make_id) VALUES(69, 'C3 Pluriel',2);
INSERT INTO models(id, model_name, make_id) VALUES(68, 'Xsara Picasso',2);
INSERT INTO models(id, model_name, make_id) VALUES(1225, 'C5',2);
INSERT INTO models(id, model_name, make_id) VALUES(1272, 'C3 Picasso',2);
INSERT INTO models(id, model_name, make_id) VALUES(101, 'C8',2);
INSERT INTO models(id, model_name, make_id) VALUES(881, 'C6',2);
INSERT INTO models(id, model_name, make_id) VALUES(267, 'C1',2);
INSERT INTO models(id, model_name, make_id) VALUES(1297, 'Berlingo',2);
INSERT INTO models(id, model_name, make_id) VALUES(100, 'Xsara',2);
INSERT INTO models(id, model_name, make_id) VALUES(987, 'C4 Picasso',2);
INSERT INTO models(id, model_name, make_id) VALUES(1207, 'Twingo',3);
INSERT INTO models(id, model_name, make_id) VALUES(657, 'Clio III',3);
INSERT INTO models(id, model_name, make_id) VALUES(70, 'Clio Storia',3);
INSERT INTO models(id, model_name, make_id) VALUES(1237, 'Koleos',3);
INSERT INTO models(id, model_name, make_id) VALUES(1241, 'Megane III',3);
INSERT INTO models(id, model_name, make_id) VALUES(1210, 'Kangoo',3);
INSERT INTO models(id, model_name, make_id) VALUES(1221, 'Modus',3);
INSERT INTO models(id, model_name, make_id) VALUES(1263, 'Clio III Facelift',3);
INSERT INTO models(id, model_name, make_id) VALUES(1276, 'Scenic',3);
INSERT INTO models(id, model_name, make_id) VALUES(74, 'Megane II',3);
INSERT INTO models(id, model_name, make_id) VALUES(1204, 'Laguna',3);
INSERT INTO models(id, model_name, make_id) VALUES(1273, 'Agila',4);
INSERT INTO models(id, model_name, make_id) VALUES(80, 'Vivaro',4);
INSERT INTO models(id, model_name, make_id) VALUES(53, 'Movano',4);
INSERT INTO models(id, model_name, make_id) VALUES(1095, 'Astra III',4);
INSERT INTO models(id, model_name, make_id) VALUES(49, 'Astra II Classic',4);
INSERT INTO models(id, model_name, make_id) VALUES(46, 'Vectra',4);
INSERT INTO models(id, model_name, make_id) VALUES(51, 'Zafira',4);
INSERT INTO models(id, model_name, make_id) VALUES(47, 'Stara Corsa',4);
INSERT INTO models(id, model_name, make_id) VALUES(81, 'Combo',4);
INSERT INTO models(id, model_name, make_id) VALUES(258, 'Speedster',4);
INSERT INTO models(id, model_name, make_id) VALUES(257, 'Tigra Twintop',4);
INSERT INTO models(id, model_name, make_id) VALUES(54, 'Meriva',4);
INSERT INTO models(id, model_name, make_id) VALUES(48, 'Stara Astra III',4);
INSERT INTO models(id, model_name, make_id) VALUES(870, 'Corsa',4);
INSERT INTO models(id, model_name, make_id) VALUES(1262, 'Insignia',4);
INSERT INTO models(id, model_name, make_id) VALUES(52, 'Signum',4);
INSERT INTO models(id, model_name, make_id) VALUES(1174, 'Antara',4);
INSERT INTO models(id, model_name, make_id) VALUES(50, 'Stara Agila',4);
INSERT INTO models(id, model_name, make_id) VALUES(1254, 'Tiguan',5);
INSERT INTO models(id, model_name, make_id) VALUES(994, 'Touran',5);
INSERT INTO models(id, model_name, make_id) VALUES(1244, 'Polo',5);
INSERT INTO models(id, model_name, make_id) VALUES(1240, 'Golf',5);
INSERT INTO models(id, model_name, make_id) VALUES(1253, 'Scirocco',5);
INSERT INTO models(id, model_name, make_id) VALUES(535, 'Jetta',5);
INSERT INTO models(id, model_name, make_id) VALUES(261, 'Passat',5);
INSERT INTO models(id, model_name, make_id) VALUES(1274, 'Touareg',5);
INSERT INTO models(id, model_name, make_id) VALUES(27, 'Sharan',5);
INSERT INTO models(id, model_name, make_id) VALUES(25, 'New Bettle',5);
INSERT INTO models(id, model_name, make_id) VALUES(43, 'Caddy',5);
INSERT INTO models(id, model_name, make_id) VALUES(920, 'Roomster',6);
INSERT INTO models(id, model_name, make_id) VALUES(1243, 'Superb',6);
INSERT INTO models(id, model_name, make_id) VALUES(1181, 'Fabia',6);
INSERT INTO models(id, model_name, make_id) VALUES(1242, 'Octavia',6);
INSERT INTO models(id, model_name, make_id) VALUES(109, 'Octavia Tour',6);
INSERT INTO models(id, model_name, make_id) VALUES(108, 'Octavia',6);
INSERT INTO models(id, model_name, make_id) VALUES(1270, 'Yaris',7);
INSERT INTO models(id, model_name, make_id) VALUES(1080, 'Hilux',7);
INSERT INTO models(id, model_name, make_id) VALUES(60, 'Land Cruiser',7);
INSERT INTO models(id, model_name, make_id) VALUES(1209, 'Land Cruiser V8',7);
INSERT INTO models(id, model_name, make_id) VALUES(1180, 'Corolla Verso',7);
INSERT INTO models(id, model_name, make_id) VALUES(1293, 'Verso',7);
INSERT INTO models(id, model_name, make_id) VALUES(1101, 'Auris',7);
INSERT INTO models(id, model_name, make_id) VALUES(1255, 'RAV4',7);
INSERT INTO models(id, model_name, make_id) VALUES(57, 'Avensis',7);
INSERT INTO models(id, model_name, make_id) VALUES(1271, 'Urban Cruiser',7);
INSERT INTO models(id, model_name, make_id) VALUES(1246, 'iQ',7);
INSERT INTO models(id, model_name, make_id) VALUES(1170, 'Corolla',7);
INSERT INTO models(id, model_name, make_id) VALUES(539, 'Aygo',7);
INSERT INTO models(id, model_name, make_id) VALUES(1295, 'Avensis',7);
INSERT INTO models(id, model_name, make_id) VALUES(1248, 'Fiesta',8);
INSERT INTO models(id, model_name, make_id) VALUES(852, 'S-Max',8);
INSERT INTO models(id, model_name, make_id) VALUES(1250, 'Focus',8);
INSERT INTO models(id, model_name, make_id) VALUES(1156, 'Mondeo',8);
INSERT INTO models(id, model_name, make_id) VALUES(1169, 'Ranger',8);
INSERT INTO models(id, model_name, make_id) VALUES(1232, 'Kuga',8);
INSERT INTO models(id, model_name, make_id) VALUES(1186, 'C-Max',8);
INSERT INTO models(id, model_name, make_id) VALUES(96, 'Fusion',8);
INSERT INTO models(id, model_name, make_id) VALUES(1249, 'Ka',8);
INSERT INTO models(id, model_name, make_id) VALUES(99, 'Galaxy',8);
INSERT INTO models(id, model_name, make_id) VALUES(942, 'Nubira/Lacetti',9);
INSERT INTO models(id, model_name, make_id) VALUES(941, 'Spark/Matiz',9);
INSERT INTO models(id, model_name, make_id) VALUES(940, 'Rezzo/Tacuma',9);
INSERT INTO models(id, model_name, make_id) VALUES(937, 'Captiva',9);
INSERT INTO models(id, model_name, make_id) VALUES(938, 'Epica',9);
INSERT INTO models(id, model_name, make_id) VALUES(943, 'Aveo/Kalos',9);
INSERT INTO models(id, model_name, make_id) VALUES(554, 'TRIBUTE',10);
INSERT INTO models(id, model_name, make_id) VALUES(1219, '6',10);
INSERT INTO models(id, model_name, make_id) VALUES(1264, 'CX-7',10);
INSERT INTO models(id, model_name, make_id) VALUES(1220, '2',10);
INSERT INTO models(id, model_name, make_id) VALUES(553, '5',10);
INSERT INTO models(id, model_name, make_id) VALUES(1200, 'BT-50',10);
INSERT INTO models(id, model_name, make_id) VALUES(172, 'MPV',10);
INSERT INTO models(id, model_name, make_id) VALUES(173, 'MX-5',10);
INSERT INTO models(id, model_name, make_id) VALUES(174, 'RX-8',10);
INSERT INTO models(id, model_name, make_id) VALUES(1288, '3',10);
INSERT INTO models(id, model_name, make_id) VALUES(1233, 'Q5',11);
INSERT INTO models(id, model_name, make_id) VALUES(177, 'A3',11);
INSERT INTO models(id, model_name, make_id) VALUES(793, 'Q7',11);
INSERT INTO models(id, model_name, make_id) VALUES(1234, 'A6',11);
INSERT INTO models(id, model_name, make_id) VALUES(181, 'TT',11);
INSERT INTO models(id, model_name, make_id) VALUES(182, 'A6 Allroad',11);
INSERT INTO models(id, model_name, make_id) VALUES(178, 'A4',11);
INSERT INTO models(id, model_name, make_id) VALUES(180, 'A8',11);
INSERT INTO models(id, model_name, make_id) VALUES(179, 'A6',11);
INSERT INTO models(id, model_name, make_id) VALUES(1184, 'A5',11);
INSERT INTO models(id, model_name, make_id) VALUES(1206, 'A4',11);
INSERT INTO models(id, model_name, make_id) VALUES(1227, 'A3',11);
INSERT INTO models(id, model_name, make_id) VALUES(1176, 'Linea',12);
INSERT INTO models(id, model_name, make_id) VALUES(217, 'Barchetta',12);
INSERT INTO models(id, model_name, make_id) VALUES(1202, '500',12);
INSERT INTO models(id, model_name, make_id) VALUES(104, 'Albea',12);
INSERT INTO models(id, model_name, make_id) VALUES(88, 'Seicento',12);
INSERT INTO models(id, model_name, make_id) VALUES(1153, 'Bravo',12);
INSERT INTO models(id, model_name, make_id) VALUES(590, 'Grande Punto',12);
INSERT INTO models(id, model_name, make_id) VALUES(266, 'Croma',12);
INSERT INTO models(id, model_name, make_id) VALUES(90, 'Panda',12);
INSERT INTO models(id, model_name, make_id) VALUES(91, 'Idea',12);
INSERT INTO models(id, model_name, make_id) VALUES(89, 'Punto',12);
INSERT INTO models(id, model_name, make_id) VALUES(85, 'Stare Doblo',12);
INSERT INTO models(id, model_name, make_id) VALUES(1218, 'Ducato',12);
INSERT INTO models(id, model_name, make_id) VALUES(92, 'Multipla',12);
INSERT INTO models(id, model_name, make_id) VALUES(1267, 'Qubo',12);
INSERT INTO models(id, model_name, make_id) VALUES(87, 'Stilo',12);
INSERT INTO models(id, model_name, make_id) VALUES(591, 'Doblo',12);
INSERT INTO models(id, model_name, make_id) VALUES(1282, 'Sedici',12);
INSERT INTO models(id, model_name, make_id) VALUES(86, 'Ulysse',12);
INSERT INTO models(id, model_name, make_id) VALUES(159, 'Z4',13);
INSERT INTO models(id, model_name, make_id) VALUES(1127, 'X5',13);
INSERT INTO models(id, model_name, make_id) VALUES(158, 'X5',13);
INSERT INTO models(id, model_name, make_id) VALUES(1230, 'X6',13);
INSERT INTO models(id, model_name, make_id) VALUES(1235, '3',13);
INSERT INTO models(id, model_name, make_id) VALUES(157, 'X3',13);
INSERT INTO models(id, model_name, make_id) VALUES(153, '5',13);
INSERT INTO models(id, model_name, make_id) VALUES(156, '7',13);
INSERT INTO models(id, model_name, make_id) VALUES(155, '6',13);
INSERT INTO models(id, model_name, make_id) VALUES(154, '3',13);
INSERT INTO models(id, model_name, make_id) VALUES(1121, '5',13);
INSERT INTO models(id, model_name, make_id) VALUES(152, '1',13);
INSERT INTO models(id, model_name, make_id) VALUES(1198, '6',13);
INSERT INTO models(id, model_name, make_id) VALUES(1114, '1',13);
INSERT INTO models(id, model_name, make_id) VALUES(1236, '7',13);
INSERT INTO models(id, model_name, make_id) VALUES(1286, 'GLK',14);
INSERT INTO models(id, model_name, make_id) VALUES(203, 'M',14);
INSERT INTO models(id, model_name, make_id) VALUES(194, 'C',14);
INSERT INTO models(id, model_name, make_id) VALUES(1157, 'B',14);
INSERT INTO models(id, model_name, make_id) VALUES(202, 'CL',14);
INSERT INTO models(id, model_name, make_id) VALUES(199, 'SLR',14);
INSERT INTO models(id, model_name, make_id) VALUES(197, 'SLK',14);
INSERT INTO models(id, model_name, make_id) VALUES(195, 'E',14);
INSERT INTO models(id, model_name, make_id) VALUES(201, 'CLS',14);
INSERT INTO models(id, model_name, make_id) VALUES(200, 'CLK',14);
INSERT INTO models(id, model_name, make_id) VALUES(198, 'SL',14);
INSERT INTO models(id, model_name, make_id) VALUES(196, 'S',14);
INSERT INTO models(id, model_name, make_id) VALUES(193, 'A',14);
INSERT INTO models(id, model_name, make_id) VALUES(1132, 'C',14);
INSERT INTO models(id, model_name, make_id) VALUES(1285, 'G',14);
INSERT INTO models(id, model_name, make_id) VALUES(1182, 'GL',14);
INSERT INTO models(id, model_name, make_id) VALUES(204, 'G',14);
INSERT INTO models(id, model_name, make_id) VALUES(1283, 'B',14);
INSERT INTO models(id, model_name, make_id) VALUES(1279, 'A',14);
INSERT INTO models(id, model_name, make_id) VALUES(1179, 'M',14);
INSERT INTO models(id, model_name, make_id) VALUES(1281, 'E',14);
