<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MakeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MakeRepository extends EntityRepository
{
    public function getMakes()
    {
        $categories = $this->createQueryBuilder('m1')
            ->select('m1, m2')
            ->leftJoin('m1.models', 'm2')
            ->getQuery()
            //->useResultCache(true, 3600);
            ;

        return $categories->execute();
    }
}
