<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
    public function getByModel($modelId)
    {
        $categories = $this->createQueryBuilder('n')
            ->select('n')
            ->leftJoin('n.models', 'm')
            ->andWhere('m.id = :id')
            ->setParameter('id', $modelId)
            ->orderBy('n.priority')
            ->getQuery()
            //->useResultCache(true, 3600);
        ;

        return $categories->execute();
    }
}
